server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eduardoshibukawa-tw/quotes-configuration
          default-label: main
          clone-on-start: true
          search-paths:
            - '{application}'
            - toggles
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456